sonar.projectKey=towns-and-nations
sonar.projectName=TownsAndNations
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/build/**,**/.gradle/**,**/gradle/**,**/out/**,**/.idea/**,**/*.md,**/src/test/**,**/src/main/resources/lang/**,**/src/main/resources/menu/**
sonar.coverage.exclusions=**/src/test/**
